name: Flutter DevSecOps Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  static-analysis:
    name: Analyse Statique CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install dependencies
        # On entre dans le dossier 'untitled' avant de lancer la commande
        run: flutter pub get
        working-directory: untitled 

      - name: Static Analysis
        # Analyse SAST pour détecter les erreurs de code
        run: flutter analyze
        working-directory: untitled

  dependency-scan:
    name: Analyse SCA (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: 'untitled' 
          format: 'table'
          severity: 'HIGH,CRITICAL'
