name: Flutter DevSecOps Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Analyse Statique (SAST)
  static-analysis:
    name: Analyse Statique CodeQL
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: untitled # C'est ici que GitHub va chercher ton code
    steps:
      - uses: actions/checkout@v4
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
      - name: Install dependencies
        run: flutter pub get
      - name: Static Analysis
        run: flutter analyze # Analyse de sécurité SAST

  # JOB 2: Analyse des Dépendances (SCA)
  dependency-scan:
    name: Analyse SCA (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Scan dependencies
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          # On scanne spécifiquement le dossier untitled
          scan-ref: 'untitled' 
          format: 'table'
          severity: 'HIGH,CRITICAL'
