name: Flutter DevSecOps Pipeline
on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  # JOB 1: Analyse Statique (SAST)
  static-analysis:
    name: Analyse Statique CodeQL
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'
          cache: true

      - name: Install dependencies
        # Remplace 'NOM_DE_TON_DOSSIER' par le nom exact du dossier qui contient ton code (ex: untitled)
        run: flutter pub get
        working-directory: . 

      - name: Static Analysis
        # Détecte les failles de sécurité dans le code source
        run: flutter analyze
        working-directory: .

  # JOB 2: Analyse des Dépendances (SCA)
  dependency-scan:
    name: Analyse SCA (Trivy)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Scan dependencies
        # Vérifie la sécurité des bibliothèques tierces
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          severity: 'HIGH,CRITICAL'
